version: '3.5'
services:
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
  backend:
    image: prudhveee/recipe-finder-backend:latest
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb+srv://pru:123@cluster0.rhvlm1b.mongodb.net/
      - PORT=8000
  frontend:
    image: prudhveee/recipe-finder-frontend:latest
    ports:
      - '3000:3000'