version: '3.5'
services:
  backend:
    image: prudhveee/recipe-finder-backend:latest
    ports:
      - '5000:5000'
    environment:
      - DB_URL=mongodb+srv://pru:123@cluster0.rhvlm1b.mongodb.net/
      - PORT=5000
  frontend:
    image: prudhveee/recipe-finder-frontend:latest
    ports:
      - '3000:3000'