version: '3.5'
services:    
  backend:
    image: laxmisreenivas/pixture-server:latest
    ports:
      - '5000:5000'
    environment:
      - DB_URL=mongodb+srv://pru:123@cluster0.rhvlm1b.mongodb.net/
      - PORT=5000
  